---


- name: Create namespaces
  redhat.openshift.k8s:
    definition: "{{ _namespace }}"
  loop: "{{ _namespaces }}"
  loop_control:
    loop_var: _namespace

- name: Create operator group {{ _operator_group.metadata.name }}
  redhat.openshift.k8s:
    definition: "{{ _operator_group }}"

- name: Install operator
  redhat.openshift.k8s:
    definition: "{{ _subscription }}"

- name: Deploy hyperconverged instance
  redhat.openshift.k8s:
    definition: "{{ _hyperconvered }}"
  register: _instance_deploy
  until:
    - not _instance_deploy.failed
  retries: 30
  delay: 30
