---

_namespace:
  apiVersion: v1
  kind: Namespace
  metadata:
    name: openshift-local-storage

_operator_group:
  apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: local-operator-group
    namespace: openshift-local-storage
  spec:
    targetNamespaces:
    - openshift-local-storage

_subscription:
  apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: local-storage-operator
    namespace: openshift-local-storage
  spec:
    channel: "stable"
    installPlanApproval: Automatic
    name: local-storage-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace

_local_volume_discovery:
  apiVersion: local.storage.openshift.io/v1alpha1
  kind: LocalVolumeDiscovery
  metadata:
    name: auto-discover-devices
    namespace: openshift-local-storage
  spec:
    nodeSelector:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: "{{ openshift | json_query('control_nodes[*].name') }}"

_volume_set:
  apiVersion: local.storage.openshift.io/v1alpha1
  kind: LocalVolumeSet
  metadata:
    name: local-disks
    namespace: openshift-local-storage
  spec:
    storageClassName: local-disks
    volumeMode: Block
    deviceInclusionSpec:
      deviceTypes: 
        - disk
      deviceMechanicalProperties:
        - NonRotational