---

_namespace:
  apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      openshift.io/cluster-monitoring: "true"
    name: openshift-storage

_operator_group:
  apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: openshift-storage-operatorgroup
    namespace: openshift-storage
  spec:
    targetNamespaces:
      - openshift-storage

_subscription:
  apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: odf-operator
    namespace: openshift-storage
  spec:
    # This should be from openshift.version
    channel: "stable-4.13"
    installPlanApproval: Automatic
    name: odf-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: odf-operator.v4.13.2-rhodf

_network_attachment_definitions_config:
  cniVersion: '0.3.1'
  type: macvlan
  master: "{{ openshift.all_node_settings.storage_interface }}"
  mode: bridge
  ipam:
    type: whereabouts
    range: "{{ openshift.storage_network | default('192.168.2.0/24') }}"

_network_attachment_definitions:
  apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    name: ocs-public-cluster
    namespace: openshift-storage
  spec:
    config: "{{ _network_attachment_definitions_config | to_json }}"

_storage_system:
  apiVersion: odf.openshift.io/v1alpha1
  kind: StorageSystem
  metadata:
    name: ocs-storagecluster-storagesystem
    namespace: openshift-storage
  spec:
    name: ocs-storagecluster
    namespace: openshift-storage
    kind: storagecluster.ocs.openshift.io/v1


_storage_cluster:
  apiVersion: ocs.openshift.io/v1
  kind: StorageCluster
  metadata:
    annotations:
      cluster.ocs.openshift.io/local-devices: 'true'
      uninstall.ocs.openshift.io/cleanup-policy: delete
      uninstall.ocs.openshift.io/mode: graceful
    name: ocs-storagecluster
    namespace: openshift-storage
  spec:
    storageDeviceSets:
      - config: {}
        count: 12
        dataPVCTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: '1'
            storageClassName: local-disks
            volumeMode: Block
        name: ocs-deviceset-local-disks
        replica: 1
    monDataDirHostPath: /var/lib/rook
    network:
      provider: multus
      selectors:
        cluster: openshift-storage/ocs-public-cluster
        public: openshift-storage/ocs-public-cluster
    externalStorage: {}
    flexibleScaling: true
    failureDomain: host
    failureDomainKey: kubernetes.io/hostname
