---

_namespaces:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-cnv
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-virtualization-os-images

_operator_group:
  apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: kubevirt-hyperconverged-group
    namespace: openshift-cnv
  spec:
    targetNamespaces:
      - openshift-cnv

_subscription:
  apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: hco-operatorhub
    namespace: openshift-cnv
  spec:
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    name: kubevirt-hyperconverged
    channel: "stable"

_hyperconvered:
  apiVersion: hco.kubevirt.io/v1beta1
  kind: HyperConverged
  metadata:
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
  spec:
    featureGates:
      deployTektonTaskResources: true
      enableCommonBootImageImport: true
      nonRoot: true
      withHostPassthroughCPU: true
