---

- name: Setup OpenShift Pipelines
  hosts:
    - helper
  vars:
    install_dir: "/home/{{ ansible_user }}/install"
  module_defaults:
    redhat.openshift.k8s:
      kubeconfig: "{{ install_dir }}/auth/kubeconfig"
  tasks:
    - name: Install ocp-pipelines operator
      redhat.openshift.k8s:
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: openshift-pipelines-operator-rh
            namespace: openshift-operators
          spec:
            channel: latest
            installPlanApproval: Automatic
            name: openshift-pipelines-operator-rh
            source: redhat-operators
            sourceNamespace: openshift-marketplace
